server:
  port: 8888

spring:
    application:
      name: andre-config-server
    cloud:
      config:
        server:
          git:
            uri: https://github.com/AndreVogelsanger/andre-config-server
            default-label: main
            search-paths:
              - 'greeting-service*'

